ad ad analytics events
applicaster/quick-brick-official-plugins pull request #70
Opened 2020-08-24 13:29 UTC by shaymark

https://applicaster.atlassian.net/browse/IM-832

added this events:
1. Video Ad Play
2. Video Ad completed
3. Video Ad Playing (Heartbeat)

4. Video ad skiped - not sure need to add it - i saw it inside  OlympicChannelPlayerAnalyticsPlugins - (when error)

i wanted these event to go to throwout the OlympicChannelPlayerAnalytics so i added 
playerOnAdStarted, playerOnAdCompleted, playerOnAdSkiped, playerOnAdProgressUpdate, to the PlayerObserverProtocol protocol.

is there a other way to do this without changing the PlayerObserverProtocol?

also i copied the files from the version i have and saw there are more changes - like 
        if adDisplayContainer == adDisplayContainer {
            adDisplayContainer?.adContainer.accessibilityIdentifier = ""
        }
where are those changes come from?

2020-08-24 20:06 UTC, snooky23 requested changes

2020-08-24 20:06 UTC, snooky23 commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
Why do you need this timer?

2020-08-25 06:41 UTC, shaymark commented
@snooky23 
so send the event without parameters? 
all the other parameters for the regular video are added inside the collectProperties method of the "Olyimpic Channel Player Analyitcs plugin", copy the logic from there or not needed?

2020-08-26 14:54 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +//             if let player = self.avPlayer, player.rate > 0 && self.isPlaybackPaused {
Remove commented code

2020-08-26 14:54 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +        print("sendEvent form observeValue rate")
Remove print

2020-08-26 14:55 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +        FacadeConnector.connector?.playerDependant?.playerAdCompleted(player: playerPlugin!)
If playerPlugin is nil it will crash

2020-08-26 14:55 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +        FacadeConnector.connector?.playerDependant?.playerAdStarted(player: playerPlugin!)
If playerPlugin is nil it will crash

2020-08-26 14:55 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +            FacadeConnector.connector?.playerDependant?.playerAdSkiped(player: playerPlugin!)
If playerPlugin is nil it will crash

2020-08-26 14:55 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +        FacadeConnector.connector?.playerDependant?.playerAdProgressUpdate(player: playerPlugin!, currentTime: mediaTime, duration: totalTime)
If playerPlugin is nil it will crash

2020-08-26 14:56 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
Why ? :)

2020-08-26 14:56 UTC, kononenkoAnton commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +                    print("sendEvent form observeValue rate pause")
Remove print

2020-08-26 15:49 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +//             if let player = self.avPlayer, player.rate > 0 && self.isPlaybackPaused {
removed

2020-08-26 15:49 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +        FacadeConnector.connector?.playerDependant?.playerAdCompleted(player: playerPlugin!)
changed

2020-08-26 15:50 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +        FacadeConnector.connector?.playerDependant?.playerAdStarted(player: playerPlugin!)
changed

2020-08-26 15:50 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +            FacadeConnector.connector?.playerDependant?.playerAdSkiped(player: playerPlugin!)
changed

2020-08-26 15:50 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter+IMAAdsManagerDelegate.swift
> +        FacadeConnector.connector?.playerDependant?.playerAdProgressUpdate(player: playerPlugin!, currentTime: mediaTime, duration: totalTime)
changed

2020-08-26 15:50 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +                    print("sendEvent form observeValue rate pause")
removed

2020-08-26 17:05 UTC, shaymark commented on plugins/ZappGoogleInteractiveMediaAds/Universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +                    print("sendEvent form observeValue rate pause")
removed 0.1 delay

2020-08-27 15:37 UTC, merged